### PR TITLE
add noopener noreferrer to developer website link

### PR DESCRIPTION
**Pull request by alikon**
As reported https://github.com/joomla/joomla-cms/issues/28978
added the `rel="noopener noreferrer"` to developer website link

### CODE REVIEW

**Comment by brianteeman** [comment]
Shouldn't the other external links also be updated

**Comment by alikon** [comment]
the original issue was only about the developer link.... 
but if we can have a consensus....  why not ....

**Comment by brianteeman** [comment]
All the external links should have noreferrer etc
They do in joomla itself so they should do here. In fact its even more important here

**Comment by alikon** [comment]
silly question 
even all the JED links should be considered as external link ?

i mean all the `<a target="_blank"` links on 
https://github.com/joomla/install-from-web-server/blob/master/components/com_apps/layouts/apps/j4/extensions_full.php
and on
https://github.com/joomla/install-from-web-server/blob/master/components/com_apps/layouts/apps/j3/extensions_full.php

**Comment by alikon** [comment]
the change will be really cheap, but i'm a bit scared about different opinions

**Comment by conconnl** [comment]
@JazParkyn can you share the opinion from JED point of view?
Do you agree with @alikon ?
I do as links go to another site and not the one you are working on.

**Comment by JazParkyn** [comment]
I don’t think there’s any question here, all external links should have rel="noopener noreferrer"

**Comment by alikon** [comment]
fair enough for me,
please double check if i've missed some urls

**Pull request merged**
