### PR TITLE
[J4] Simple search accessibility

### PR DESCRIPTION
**Pull request by brianteeman**
Ensures that buttons and labels have appropriate values.

(I am working blind here as I haven't worked out how to view this locally - any ideas to resolve that would be great as there is more to do)

### CODE REVIEW

**Comment by mbabker** [comment]
> I am working blind here as I haven't worked out how to view this locally - any ideas to resolve that would be great as there is more to do

The way I did it was I cloned this repo to my system, symlinked the component into a Joomla install (it should run on 4.0 no problem IIRC), discover installed it into the site, then changed the server URL in the plugin to point to the local install.

**Comment by brianteeman** [comment]
thanks for the tip

**Comment by brianteeman** [comment]
not having any joy with discover - its not finding anything

**Comment by mbabker** [comment]
```sql
INSERT INTO `#__extensions` (`package_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`)
VALUES
	(0, 'Apps', 'component', 'com_apps', '', 1, 1, 1, 0, '{\"name\":\"Apps\",\"type\":\"component\",\"creationDate\":\"2013-08-22\",\"author\":\"Joomla! Development Team\",\"copyright\":\"Copyright 2013 Joomla!.\",\"authorEmail\":\"joomla@joomla.com\",\"authorUrl\":\"www.joomla.com\",\"version\":\"1.0\",\"description\":\"Description\",\"group\":\"\"}', '{\"cdn\":\"https:\\/\\/extensionscdn.joomla.org\\/\",\"route_prefix\":\"index.php?option=com_apps&format=json\",\"default_limit\":128}', '', '', 0, '0000-00-00 00:00:00', 0, 0);
```

With the paths symlinked that should essentially do the one step that the discover install actually would, add it to the database.

**Comment by brianteeman** [comment]
Thanks - afraid I gave up getting it working locally for now

**Pull request merged**
